In [1]:
# 读取numpy文件 https://docs.scipy.org/doc/numpy/reference/generated/numpy.genfromtxt.html#numpy.genfromtxt
import numpy
world_alcohol = numpy.genfromtxt("world_alcohol.txt", delimiter=",", dtype=str)
print ('world_alcohol的类型：\n', type(world_alcohol))
print ('world_alcohol的详细信息：\n', world_alcohol)
print ('world_alcohol第2行第2列元素值：\n', world_alcohol[2,2]) 

world_alcohol的类型：
 <class 'numpy.ndarray'>
world_alcohol的详细信息：
 [['Year' 'WHO region' 'Country' 'Beverage Types' 'Display Value']
 ['1986' 'Western Pacific' 'Viet Nam' 'Wine' '0']
 ['1986' 'Americas' 'Uruguay' 'Other' '0.5']
 ...
 ['1987' 'Africa' 'Malawi' 'Other' '0.75']
 ['1989' 'Americas' 'Bahamas' 'Wine' '1.5']
 ['1985' 'Africa' 'Malawi' 'Spirits' '0.31']]
world_alcohol第2行第2列元素值：
 Uruguay


In [2]:
# 向量
vector = numpy.array([5, 10, 15, 20])
print ('向量\n', vector)
print ('向量形状\n', vector.shape)
print ('向量前3个元素值\n', vector[:3])
print ('元素值判断\n', vector==10)
print ('取元素值==10的元素', vector[vector==10])
print ('取既等于10又等于5的元素', vector[(vector==10) & (vector==5)])
print ('取等于或等于5的元素', vector[(vector==10) | (vector == 5)])
vector[(vector==10) | (vector==5)] = 50
print ('对等于10或等于5的元素赋值50',  vector)
# 矩阵
matrix = numpy.array([[5, 10, 15], [20, 25, 30], [35, 40, 45]])
print ('矩阵\n', matrix)
print ('矩阵形状\n', matrix.shape)
print ('矩阵第1列元素值\n', matrix[:,1])
print ('矩阵前2列元素值\n', matrix[:,0:2])
print ('矩阵第1,2行，前2列元素\n', matrix[1:3, 0:2])
print ('元素值判断\n', matrix == 20)
print ('取第1列中元素值==25的元素所在行', matrix[matrix[:,1]==25,:])

向量
 [ 5 10 15 20]
向量形状
 (4,)
向量前3个元素值
 [ 5 10 15]
元素值判断
 [False  True False False]
取元素值==10的元素 [10]
取既等于10又等于5的元素 []
取等于或等于5的元素 [ 5 10]
对等于10或等于5的元素赋值50 [50 50 15 20]
矩阵
 [[ 5 10 15]
 [20 25 30]
 [35 40 45]]
矩阵形状
 (3, 3)
矩阵第1列元素值
 [10 25 40]
矩阵前2列元素值
 [[ 5 10]
 [20 25]
 [35 40]]
矩阵第1,2行，前2列元素
 [[20 25]
 [35 40]]
元素值判断
 [[False False False]
 [ True False False]
 [False False False]]
取第1列中元素值==25的元素所在行 [[20 25 30]]


In [3]:
# 矩阵元素类型转换
vector = numpy.array(["1", "2", "3"])
print (vector.dtype)
print (vector)
vector = vector.astype(float)
print (vector.dtype)
print (vector)

<U1
['1' '2' '3']
float64
[1. 2. 3.]


In [4]:
# 向量求极值
vector = numpy.array([5, 10, 15, 20])
vector.min()

5

In [5]:
matrix = numpy.array([[5, 10, 15],
                      [20, 25, 30],
                      [35, 40, 45]])
# 矩阵按行求和
print ('矩阵按行求和：', matrix.sum(axis=1))
# 矩阵按列求和
print ('矩阵按列求和：', matrix.sum(axis=0))

矩阵按行求和： [ 30  75 120]
矩阵按列求和： [60 75 90]


In [6]:
# arange函数1
import numpy as np
a = np.arange(15)
print ('arange函数生成向量a：', a)
print ('a的类型：', type(a))
print ('a元素的类型：', a.dtype.name)
print ('a的维度：', a.ndim)
print ('a的形状：', a.shape)
print ('a中元素个数：', a.size)
# reshape函数
b = a.reshape(3, 5)
print ('a变成3*5矩阵b：\n', b)
print ('b的类型：', type(b))
print ('b元素的类型：', b.dtype.name)
print ('b的维度：', b.ndim)
print ('b的形状：', b.shape)
print ('b中元素个数：',b.size)
# arange函数2
print ('arange函数生成向量c：', np.arange(10, 30, 5))
print ('arange函数生成向量d：', np.arange(0, 2, 0.3))
# linspace函数
from numpy import pi
print ('linspace函数生成指定区间和个数的向量e：', np.linspace(0, 2*pi, 100))

arange函数生成向量a： [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
a的类型： <class 'numpy.ndarray'>
a元素的类型： int32
a的维度： 1
a的形状： (15,)
a中元素个数： 15
a变成3*5矩阵b：
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
b的类型： <class 'numpy.ndarray'>
b元素的类型： int32
b的维度： 2
b的形状： (3, 5)
b中元素个数： 15
arange函数生成向量c： [10 15 20 25]
arange函数生成向量d： [0.  0.3 0.6 0.9 1.2 1.5 1.8]
linspace函数生成指定区间和个数的向量e： [0.         0.06346652 0.12693304 0.19039955 0.25386607 0.31733259
 0.38079911 0.44426563 0.50773215 0.57119866 0.63466518 0.6981317
 0.76159822 0.82506474 0.88853126 0.95199777 1.01546429 1.07893081
 1.14239733 1.20586385 1.26933037 1.33279688 1.3962634  1.45972992
 1.52319644 1.58666296 1.65012947 1.71359599 1.77706251 1.84052903
 1.90399555 1.96746207 2.03092858 2.0943951  2.15786162 2.22132814
 2.28479466 2.34826118 2.41172769 2.47519421 2.53866073 2.60212725
 2.66559377 2.72906028 2.7925268  2.85599332 2.91945984 2.98292636
 3.04639288 3.10985939 3.17332591 3.23679243 3.30025895 3.36372547
 3.42719199 3.49065

In [7]:
# 全0矩阵
print ('全0矩阵：\n', np.zeros((3,4)))
# 全1矩阵
print ('全1矩阵：\n', np.ones((2,3,4), dtype=np.int32))

全0矩阵：
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
全1矩阵：
 [[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]


In [8]:
# 随机初始化矩阵 https://docs.scipy.org/doc/numpy/reference/generated/numpy.random.random.html#numpy.random.random
print ('随机初始化矩阵：\n', np.random.random((2, 3)))

随机初始化矩阵：
 [[0.42916014 0.75200512 0.80929323]
 [0.65669041 0.32626574 0.19658161]]


In [9]:
# 向量加减乘方
a = np.array([20, 30, 40, 50])
b = np.arange(4)
print ('a=', a)
print ('b=', b)
c = a-b
print ('c=a-b\n', a-b)
print ('a*2\n', a*2)
print ('c-1\n', c-1)
print ('b**2\n', b**2)
print ('a<35\n', a<35)

a= [20 30 40 50]
b= [0 1 2 3]
c=a-b
 [20 29 38 47]
a*2
 [ 40  60  80 100]
c-1
 [19 28 37 46]
b**2
 [0 1 4 9]
a<35
 [ True  True False False]


In [10]:
# 矩阵乘法和内积
A = np.array([[1, 1],
              [0, 1]])
B = np.array([[2, 0],
              [3, 4]])
print ('矩阵A\n', A)
print ('矩阵B\n', B)
print ('A与B的点积\n', A*B)
print ('矩阵乘法\n', A.dot(B))
print ('矩阵乘法\n', np.dot(A, B))

矩阵A
 [[1 1]
 [0 1]]
矩阵B
 [[2 0]
 [3 4]]
A与B的点积
 [[2 0]
 [0 4]]
矩阵乘法
 [[5 4]
 [3 4]]
矩阵乘法
 [[5 4]
 [3 4]]


In [11]:
# 向量中每个元素求指数
import numpy as np
B = np.arange(3)
print ('B=\n', B)
print ('B中每个元素求指数：\n', np.exp(B))
print ('B中每个元素求平方根：\n', np.sqrt(B))

B=
 [0 1 2]
B中每个元素求指数：
 [1.         2.71828183 7.3890561 ]
B中每个元素求平方根：
 [0.         1.         1.41421356]


In [12]:
# 生成3*4的随机矩阵，矩阵元素取值范围为[0,10),对于随机生成的数值扩充10倍后向下取整
A = np.floor(10*np.random.random((3,4)))
print ('A=\n', A)
# 矩阵转成向量
print ('A转成向量：\n', A.ravel())
# reshape的另一种方式
A.shape = (6, 2)
print ('对矩阵A重新变换形状：\n', A)
# 矩阵的转置
print ('矩阵A的转置：\n', A.T)
# reshape自动确定维数
A = A.reshape(3, -1)
print ('矩阵A重新变换形状2：\n', A)

A=
 [[8. 6. 6. 6.]
 [1. 1. 4. 4.]
 [8. 5. 5. 4.]]
A转成向量：
 [8. 6. 6. 6. 1. 1. 4. 4. 8. 5. 5. 4.]
对矩阵A重新变换形状：
 [[8. 6.]
 [6. 6.]
 [1. 1.]
 [4. 4.]
 [8. 5.]
 [5. 4.]]
矩阵A的转置：
 [[8. 6. 1. 4. 8. 5.]
 [6. 6. 1. 4. 5. 4.]]
矩阵A重新变换形状2：
 [[8. 6. 6. 6.]
 [1. 1. 4. 4.]
 [8. 5. 5. 4.]]


In [13]:
# 矩阵拼接
import numpy as np
A = np.floor(10*np.random.random((2, 2)))
B = np.floor(10*np.random.random((2, 2)))
print ('A=\n', A)
print ('B=\n', B)
print ('C=[A, B]=\n', np.hstack((A, B)))
print ("""D=[A
             B]=\n""", np.vstack((A, B)))

A=
 [[3. 4.]
 [0. 1.]]
B=
 [[7. 0.]
 [7. 6.]]
C=[A, B]=
 [[3. 4. 7. 0.]
 [0. 1. 7. 6.]]
D=[A
             B]=
 [[3. 4.]
 [0. 1.]
 [7. 0.]
 [7. 6.]]


In [14]:
# 矩阵分解
A = np.floor(10*np.random.random((2, 12)))
print ('A=\n', A)
print ('A按行分解为3个矩阵：\n', np.hsplit(A, 3))
print ('A按行分解指定分解位置：\n', np.hsplit(A, (3, 4)))
A = A.T
print ('A的转置：\n', A)
print ('A按列分解为3个矩阵：\n', np.vsplit(A, 3))

A=
 [[7. 3. 0. 2. 2. 7. 6. 3. 4. 7. 7. 7.]
 [3. 7. 0. 7. 0. 0. 5. 3. 3. 6. 5. 1.]]
A按行分解为3个矩阵：
 [array([[7., 3., 0., 2.],
       [3., 7., 0., 7.]]), array([[2., 7., 6., 3.],
       [0., 0., 5., 3.]]), array([[4., 7., 7., 7.],
       [3., 6., 5., 1.]])]
A按行分解指定分解位置：
 [array([[7., 3., 0.],
       [3., 7., 0.]]), array([[2.],
       [7.]]), array([[2., 7., 6., 3., 4., 7., 7., 7.],
       [0., 0., 5., 3., 3., 6., 5., 1.]])]
A的转置：
 [[7. 3.]
 [3. 7.]
 [0. 0.]
 [2. 7.]
 [2. 0.]
 [7. 0.]
 [6. 5.]
 [3. 3.]
 [4. 3.]
 [7. 6.]
 [7. 5.]
 [7. 1.]]
A按列分解为3个矩阵：
 [array([[7., 3.],
       [3., 7.],
       [0., 0.],
       [2., 7.]]), array([[2., 0.],
       [7., 0.],
       [6., 5.],
       [3., 3.]]), array([[4., 3.],
       [7., 6.],
       [7., 5.],
       [7., 1.]])]


In [15]:
# 向量的多引用
a = np.arange(12)
b = a
b.shape = (3, 4)
print ('a=\n', a)
print ('b=\n', b)
print ('id(a)=', id(a))
print ('id(b)=', id(b))
print ('='*10)
# 浅复制 两个变量指向不同的对象，但是两个对象共用同一块内存
c = a.view()
c.shape = (2, 6)
c[0, 4] = 1234
print ('a=\n', a)
print ('c=\n', c)
print ('id(a)=', id(a))
print ('id(c)=', id(c))
print ('='*10)
# 深复制 两个变量指向不同的对象，两个对象有各自的内存
d = a.copy()
d[0, 0] = 9999
print ('a=\n', a)
print ('d=\n', d)
print ('id(a)=', id(a))
print ('id(d)=', id(d))

a=
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
b=
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
id(a)= 2063907350128
id(b)= 2063907350128
a=
 [[   0    1    2    3]
 [1234    5    6    7]
 [   8    9   10   11]]
c=
 [[   0    1    2    3 1234    5]
 [   6    7    8    9   10   11]]
id(a)= 2063907350128
id(c)= 2063907349968
a=
 [[   0    1    2    3]
 [1234    5    6    7]
 [   8    9   10   11]]
d=
 [[9999    1    2    3]
 [1234    5    6    7]
 [   8    9   10   11]]
id(a)= 2063907350128
id(d)= 2063907511472


In [16]:
# 求最大值位置
import numpy as np
data = np.sin(np.arange(20).reshape(5,4))
print ('data=', data)
# 按列找最大值位置
print ('按列找矩阵每列最大值的位置', np.argmax(data, 0))
# 取出最大值
indx = np.argmax(data, 0)
print ('按列找矩阵每列最大值', data[indx, np.arange(data.shape[1])])
# 按行找最大值位置
print ('按行找矩阵每行最大值的位置', np.argmax(data, 1))

data= [[ 0.          0.84147098  0.90929743  0.14112001]
 [-0.7568025  -0.95892427 -0.2794155   0.6569866 ]
 [ 0.98935825  0.41211849 -0.54402111 -0.99999021]
 [-0.53657292  0.42016704  0.99060736  0.65028784]
 [-0.28790332 -0.96139749 -0.75098725  0.14987721]]
按列找矩阵每列最大值的位置 [2 0 3 1]
按列找矩阵每列最大值 [0.98935825 0.84147098 0.99060736 0.6569866 ]
按行找矩阵每行最大值的位置 [2 3 0 2 3]


In [17]:
# 将向量作为元素，扩充成矩阵
a = np.arange(10, 40, 10)
print ('a=', a)
B = np.tile(a, (2, 3)) # 行是原来的2倍， 列是原来的3倍
print ('B=\n', B)

a= [10 20 30]
B=
 [[10 20 30 10 20 30 10 20 30]
 [10 20 30 10 20 30 10 20 30]]


In [18]:
# 排序
A = np.array([[4, 3, 5], 
              [1, 2, 1]])
print ('A=\n', A)
# 按行排序
B = np.sort(A, axis=1)
print ('A按行排序\n', B)
# 向量按行排序方法2
a = np.array([4, 3, 1, 2])
print ('a=', a)
sort_indx = np.argsort(a)
print ('a按行排序\n', a[sort_indx])

A=
 [[4 3 5]
 [1 2 1]]
A按行排序
 [[3 4 5]
 [1 1 2]]
a= [4 3 1 2]
a按行排序
 [1 2 3 4]
